### ISSUE TITLE
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by SpeckyYT** [endertitan100/SPWN-Graphics#1]
please use `lower_case_snake_case` for filenames and spwn variables

**Comment by endertitan100** [comment]
Why?

**Comment by SpeckyYT** [comment]
> Why?

lowercase and uppercase snake cases are the convention in spwn

**Comment by endertitan100** [comment]
Ok Lemme Fix that
